### ISSUE TITLE
Dist folder is in git repo

### ISSUE THREAD

**Issue by orta** [artsy/stitch#2]
Is this intentional?

**Comment by damassi** [comment]
@orta - yup. By checking it in it makes it easier for clients to consume; no need to package up babel deps to compile on `yarn postinstall`, etc. Any thoughts about this approach?

**Comment by orta** [comment]
I'm honestly fine with both - I tend to fall on the "not including the built versions" side, as I don't enjoy seeing a PR with two sets of the same code. ( We have this faffing [with relay](https://github.com/artsy/emission/blob/master/package.json#L60) )

Which *definitely* make it harder when you want to run a branch. I think it really falls down onto "do you think it's something that we'll want to make pretty regular changes to?" in which case I think it makes sense to include the dist.

**Comment by damassi** [comment]
This is interesting -- https://www.npmjs.com/package/postinstall-build. I'm going to experiment and see how it goes

**Comment by damassi** [comment]
Yeah, these sorts of solutions are always so hacky as the issues in that repo show. `dist` folders tend to simplify and since Babel output is idempotent I'm not too worried about diffs. One PR is for features / changes / etc (doesn't include build output) and once that's merged we can run `npm publish` which runs `prepublishOnly` which then creates a build based on the merged per which can be committed directly into `master` without a PR (or in a separate PR, if necessary). 

Totally open to suggestions but for now this seems pretty straightforward!
